openapi: 3.1.1
info:
  title: Provider
  version: 2.1.0
  description: "Container schemas fetched from beckn.yaml. This cannot be extended as it is a reserved schema in beckn protocol. Any additional properties added to this schema can only be made using its *Attributes property"
  license:
    name: CC-BY-NC-SA 4.0 International
  contact:
    name: Beckn Labs
    url: https://beckn.io
components:
  schemas:
    Provider:
      type: object
      description: Schema definition for Provider in the Beckn Protocol v2.0.1
      title: Provider
      properties:
        id:
          description: Unique identifier for the provider
          type: string
          example: tech-store-001
        descriptor:
          $ref: https://schema.beckn.io/Descriptor/v2.1/attributes.yaml#/components/schemas/Descriptor
        availableAt:
          description: Physical locations where the provider operates
          type: array
          items:
            $ref: https://schema.beckn.io/Location/v2.0/attributes.yaml#/components/schemas/Location
        providerAttributes:
          $ref: https://schema.beckn.io/Attributes/v2.0/attributes.yaml#/components/schemas/Attributes
      required:
      - descriptor
      additionalProperties: false
